### ISSUE TITLE
"res" is null

### ISSUE THREAD

**Issue by monmon** [payjp/payjp-node#4]
version: 1.1.1.

There was an error log.
```
TypeError: Cannot read property 'statusCode' of undefined
    at /node/app_server/node_modules/payjp/lib/requestor.js:65:18
    at Request.callback (/node/app_server/node_modules/payjp/node_modules/superagent/lib/node/index.js:687:12)
    at /node/app_server/node_modules/payjp/node_modules/superagent/lib/node/index.js:884:43
    at IncomingMessage.<anonymous> (/node/app_server/node_modules/payjp/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

`requestor.js:65` is here.
res is null?
```
        request.end(function (err, res) {
          if (res.statusCode === 200) {
            resolve(res.body);
          } else {
            reject(err);
          }
        });
```

**Comment by darai0512** [comment]
fixed by https://github.com/payjp/payjp-node/pull/17
